name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  test:
    strategy:
      matrix:
        os:  [ 'ubuntu-latest', 'macOS-latest', 'windows-latest' ]
        go: [ '1.22', '1.23' ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}

    - name: Test
      run: go test -count=1 -v -failfast -cover ./...

    - name: Test with race detector
      run: go test -count=1 -v -race -failfast -cover ./...
